// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vuhyhsarztqdzxapvcpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1aHloc2FyenRxZHp4YXB2Y3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMjAzNDYsImV4cCI6MjA2NjY5NjM0Nn0.hiTN0Y0vzdxGETxxBY95Ea7bLraEmNzMkcO9A9J5GIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);